### PR TITLE
Do not check for existing user when requesting verification email

### LINKED ISSUE #71: /verification-email endpoint should not check for existing user in database.
## Observed behavior

Endpoints `/api/secure/user/verification-email` and `/api/secure/application/verification-email` both return 404 - unknown user for new users signed up in MOD UI or new API key users signed up in OTP Admin UI.

## Expected behavior

These endpoints should return success and should not check for existing OtpUser or ApiUser in the database.
At that stage, the database entry for these users has not been created yet (the email has not been verified yet).

## Steps to reproduce the problem

Sign up as a new user in MOD UI (requires https://github.com/opentripplanner/otp-react-redux/pull/227) or in the OTP Admin UI at https://otp-admin-ui-91byeqrw6.vercel.app/. On the email verification screen, click the button to resend the verification email. A confirmation message is shown, however the underlying network request failed with an "Unknown user" message.

## Version of otp-middleware and/or OpenTripPlanner if applicable (exact commit hash or branch name)

OTP Middleware dev or trip-monitor branch.

### PR DESCRIPTION
**Pull request by binh-dam-ibigroup**
### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JavaDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [na] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing

### Description

This PR fixes #71.

### CODE REVIEW

**Review by evansiroky — APPROVED** [review]

**Review by br648 — APPROVED** [review]
Looks good to me.

File: src/main/java/org/opentripplanner/middleware/auth/Auth0Connection.java [hunk 1]
```diff
@@ -67,7 +68,7 @@ public static void checkUser(Request req) {
             DecodedJWT jwt = verifier.verify(token);
             Auth0UserProfile profile = new Auth0UserProfile(jwt);
             if (!isValidUser(profile)) {
-                if (isCreatingSelf(req, profile)) {
+                if (isCreatingOrEmailingSelf(req, profile)) {
```
Comment (landonreed) [inline src/main/java/org/opentripplanner/middleware/auth/Auth0Connection.java]: It might be good to rename this to something a bit more generic: `missingProfileIsExpected(req, profile)`. And the below log statement could be generalized a bit too.

File: src/main/java/org/opentripplanner/middleware/auth/Auth0Connection.java [hunk 2]
```diff
@@ -115,6 +117,11 @@ private static boolean isCreatingSelf(Request req, Auth0UserProfile profile) {
                     LOG.warn("Could not parse user object from request.", e);
                 }
             }
+        } else if (method.equalsIgnoreCase("GET")) {
+            // If this a GET request, it should be against the verification-email route for /user or /application.
+            // (Email verification does not apply to admins.)
+            return uri.endsWith(API_USER_PATH + VERIFICATION_EMAIL_PATH) ||
+                uri.endsWith(OTP_USER_PATH + VERIFICATION_EMAIL_PATH);
```
Comment (landonreed) [inline src/main/java/org/opentripplanner/middleware/auth/Auth0Connection.java]: I think each of these conditional blocks should be its own method:
- `isCreatingSelf(Request req)`
- `isRequestingVerificationEmail(Request req)`

**Review by landonreed — APPROVED** [review]
Looks good, just a couple of items for conditional approval.

**Comment by binh-dam-ibigroup** [comment]
FYI, I just added tests for the self persist and email verification requests.
