### PR TITLE
Reorganize test files

### LINKED ISSUE #118: Test Util methods are unorganized
## Observed behavior

There are a number of Util methods and classes to help with testing, but they are kind of disorganized.

## Expected behavior

Testing util methods should be more organized.

### PR DESCRIPTION
**Pull request by evansiroky**
### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JavaDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [x] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing

### Description

This PR reorganizes a bunch of testing files into a hopefully more coherent organizational system (fixes #118). The following occurs in this PR:

- A new folder `testUtils` has been created that now holds a number of files that contain various utility methods used in other test files.
- The old `TestUtils` file has been split into 3 files:
  - `ApiTestUtils`
  - `CommonTestUtils`
  - `OtpTestUtils`
- All files that test various items in the API have been moved to the `api` folder.
- `RegisterRedirectTest` has been removed and the single test that was in it has been moved to the `OtpMiddleWareTest` file. The `OtpMiddlewareTest` file as a result is now no longer an abstract class so that the register redirect test case runs.
- The BugSnag test files have been moved to the `bugsnag` folder.
- The `PersistenceUtil` file has been renamed to `PersistenceTestUtils` and moved into the `testUtils` folder.
- The `OtpDispatcherResponseTest#URI DEFAULT_PLAN_URI` variable has been moved to `OtpTestUtils`.
- The resource files for OTP-related tests have all been moved into the `resources/otp/response` folder. The places where these files are read in the tests have been updated to use the correct path and a new helper method `CommonTestUtils#getResourceFileContentsAsString`
- The `PersistenceUtils` methods `getPlanResponse`, `getPlanErrorResponse` and `createItinerary` have been moved to `OtpTestUtils`.
- The `NotificationUtilsTests` file was moved to the `utils` folder.
- The `transitLeg.json` and `walkLeg.json` files were no longer used anywhere and therefore were deleted.

### CODE REVIEW

File: src/test/java/org/opentripplanner/middleware/utils/ItineraryUtilsTest.java [hunk 1]
```diff
@@ -17,6 +16,8 @@
 import org.opentripplanner.middleware.otp.response.Leg;
 import org.opentripplanner.middleware.otp.response.OtpResponse;
 import org.opentripplanner.middleware.otp.response.Place;
+import org.opentripplanner.middleware.testUtils.CommonTestUtils;
+import org.opentripplanner.middleware.testUtils.OtpTestUtils;
```
Comment (landonreed) [inline src/test/java/org/opentripplanner/middleware/utils/ItineraryUtilsTest.java]: The new package name should be all lowercase `org.opentripplanner.middleware.testutils` or   `org.opentripplanner.middleware.test_utils`.

https://stackoverflow.com/a/3179221/915811

File: src/test/java/org/opentripplanner/middleware/testUtils/CommonTestUtils.java [hunk 2]
```diff
@@ -0,0 +1,31 @@
...
+    public static boolean getBooleanEnvVar(String var) {
+        String variable = System.getenv(var);
+        return variable != null && variable.equals("true");
+    }
+
+    public static <T> T getResourceFileContentsAsJSON(String resourcePathName, Class<T> clazz) throws IOException {
+        return FileUtils.getFileContentsAsJSON(TEST_RESOURCE_PATH + resourcePathName, clazz);
+    }
+
+    public static String getResourceFileContentsAsString(String resourcePathName) throws IOException {
```
Comment (landonreed) [inline src/test/java/org/opentripplanner/middleware/testUtils/CommonTestUtils.java]: I think a better name for this method would be `CommonTestUtils#getTestResourceAsString`. Same goes for the above (`CommonTestUtils#getTestResourceAsJSON`)

File: src/test/java/org/opentripplanner/middleware/testUtils/CommonTestUtils.java [hunk 3]
```diff
@@ -0,0 +1,31 @@
...
+
+import org.opentripplanner.middleware.utils.FileUtils;
+
+import java.io.IOException;
+
+public class CommonTestUtils {
+    /**
+     * Whether the end-to-end environment variable is enabled.
+     */
+    public static final boolean isEndToEnd = getBooleanEnvVar("RUN_E2E");
```
Comment (landonreed) [inline src/test/java/org/opentripplanner/middleware/testUtils/CommonTestUtils.java]: I think maybe this should be all caps/underscore since it's static/final.

**Review by landonreed — CHANGES_REQUESTED** [review]
LGTM, just a few slight tweaks.

File: src/test/java/org/opentripplanner/middleware/utils/ItineraryUtilsTest.java (hunk 1 above)
Comment (binh-dam-ibigroup) [reply src/test/java/org/opentripplanner/middleware/utils/ItineraryUtilsTest.java]: I vote `testutils`.

File: src/test/java/org/opentripplanner/middleware/testUtils/OtpTestUtils.java [hunk 4]
```diff
@@ -0,0 +1,206 @@
...
+import static org.opentripplanner.middleware.otp.OtpDispatcher.OTP_PLAN_ENDPOINT;
+import static org.opentripplanner.middleware.utils.JsonUtils.logMessageAndHalt;
+import static spark.Service.ignite;
+
+public class OtpTestUtils {
+    private static final Logger LOG = LoggerFactory.getLogger(OtpTestUtils.class);
+    private static final ObjectMapper mapper = new ObjectMapper();
+
+    /**
+     * Prevents the mock OTP server being initialized more than once
```
Comment (binh-dam-ibigroup) [inline src/test/java/org/opentripplanner/middleware/testUtils/OtpTestUtils.java]: Typo
```
Prevents the mock OTP server being initialized...
                            ^
                            from
```

File: src/test/java/org/opentripplanner/middleware/controllers/api/Auth0ConnectionTest.java [hunk 5]
```diff
@@ -1,11 +1,12 @@
-package org.opentripplanner.middleware;
+package org.opentripplanner.middleware.controllers.api;
```
Comment (binh-dam-ibigroup) [inline src/test/java/org/opentripplanner/middleware/controllers/api/Auth0ConnectionTest.java]: I think this class should be in package `org.opentripplanner.middleware.auth` to match with `Auth0Connection`. The rationale is that tests performed in this file target `Auth0Connection#isCreatingSelf` and `Auth0Connection#isRequestingVerificationEmail` (despite the code in the tests dealing more with the api controllers than `Auth0Connection`).

File: src/test/java/org/opentripplanner/middleware/testUtils/OtpTestUtils.java [hunk 6]
```diff
@@ -0,0 +1,206 @@
...
+     * Get error plan response from file for creating trip summaries.
+     */
+    public static OtpResponse getPlanErrorResponse() throws IOException {
+        return CommonTestUtils.getResourceFileContentsAsJSON(
+            responseResourceFilePath + "planErrorResponse.json",
+            OtpResponse.class
+        );
+    }
+
+    static Itinerary createItinerary() {
```
Comment (binh-dam-ibigroup) [inline src/test/java/org/opentripplanner/middleware/testUtils/OtpTestUtils.java]: This is used only in `PersistenceTestUtils`, so I would move this test to that class.

**Review by binh-dam-ibigroup — CHANGES_REQUESTED** [review]
One class should be moved, and one helper method can probably be moved.

This refactor was needed, thanks for taking the lead on that!

File: src/test/java/org/opentripplanner/middleware/testUtils/OtpTestUtils.java (hunk 6 above)
Comment (evansiroky) [reply src/test/java/org/opentripplanner/middleware/testUtils/OtpTestUtils.java]: Moved in 695f54c4ffb08e23144a496d611b999c93c86764.

File: src/test/java/org/opentripplanner/middleware/controllers/api/Auth0ConnectionTest.java (hunk 5 above)
Comment (evansiroky) [reply src/test/java/org/opentripplanner/middleware/controllers/api/Auth0ConnectionTest.java]: Moved in 695f54c4ffb08e23144a496d611b999c93c86764.

File: src/test/java/org/opentripplanner/middleware/testUtils/OtpTestUtils.java (hunk 4 above)
Comment (evansiroky) [reply src/test/java/org/opentripplanner/middleware/testUtils/OtpTestUtils.java]: Fixed in 695f54c4ffb08e23144a496d611b999c93c86764.

File: src/test/java/org/opentripplanner/middleware/testUtils/CommonTestUtils.java (hunk 3 above)
Comment (evansiroky) [reply src/test/java/org/opentripplanner/middleware/testUtils/CommonTestUtils.java]: Changed in 695f54c4ffb08e23144a496d611b999c93c86764.

File: src/test/java/org/opentripplanner/middleware/testUtils/CommonTestUtils.java (hunk 2 above)
Comment (evansiroky) [reply src/test/java/org/opentripplanner/middleware/testUtils/CommonTestUtils.java]: Changed in 695f54c4ffb08e23144a496d611b999c93c86764.

File: src/test/java/org/opentripplanner/middleware/utils/ItineraryUtilsTest.java (hunk 1 above)
Comment (evansiroky) [reply src/test/java/org/opentripplanner/middleware/utils/ItineraryUtilsTest.java]: Changed in 695f54c4ffb08e23144a496d611b999c93c86764.

**Review by landonreed — APPROVED** [review]

**Review by binh-dam-ibigroup — APPROVED** [review]
