### PR TITLE
Reinstate same-day itin check.

### LINKED ISSUE #100: Itinerary existence should include same-day departure check
## Observed behavior

When checking the existence of an itinerary on a given day of the week, the middleware does not check whether an itinerary returned by OTP departs/arrives that same day. 

[This OTP query](https://fdot-otp.ibi-transit.com/#/?ui_activeSearch=x1ybdy69g&ui_activeItinerary=0&fromPlace=1801%20Rouse%20Road%2C%20Orlando%2C%20FL%2C%20USA%3A%3A28.56974836181537%2C-81.2238121032715&toPlace=Avalon%20Park%20Boulevard%2C%20Alafaya%2C%20FL%2C%20USA%3A%3A28.5644716598953%2C-81.16579055786134&date=2020-11-10&time=09%3A27&arriveBy=false&mode=WALK%2CBUS%2CRAIL&showIntermediateStops=true&maxWalkDistance=1207&optimize=QUICK&walkSpeed=1.34&ignoreRealtimeUpdates=true&companies=&bannedRoutes=&numItineraries=3&otherThanPreferredRoutesPenalty=900&preferredRoutes=), for instance, uses a bus route that does not operate on weekends. If you try to monitor the transit itinerary on Saturdays and Sundays, the itinerary check will determine the transit itinerary to be not possible on Saturdays, which is correct, but also possible on Sundays, which is incorrect.

Further investigation of the OTP response shows that OTP can return itineraries for the next day if none are found for the requested day (see screenshot), one of which could match the reference itinerary for the trip to be monitored.

image

## Expected behavior

For the trip query provided above, the transit itinerary should not be possible on Sundays.

## Steps to reproduce the problem

1. Open the link above and click the Walk-Bus itinerary
2. Click `Save trip`
3. Tick Saturday and Sunday to monitor the itinerary Saturdays and Sundays, then click Save.
4. Observe the error message.
 
## Version of otp-middleware and/or OpenTripPlanner if applicable (exact commit hash or branch name)

Backend: `dev` branch (commit https://github.com/ibi-group/otp-middleware/commit/ed41d0b1045f60d36f92c75391a605b327938297 or above)

Frontend: `dev` branch

### PR DESCRIPTION
**Pull request by binh-dam-ibigroup**
### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JavaDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [na] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing

### Description

This PR fixes #100 by adding back the same-day check that was used during the development as a condition of existence of an itinerary. This PR depends on #90, ~therefore the base branch is set to~ `itinerary-matching-mvp`.

### CODE REVIEW

**Review by evansiroky — APPROVED** [review]
I'm assuming this is mostly the same as the previous iteration, so I'm approving.

**Comment by evansiroky** [comment]
As per our recent discussion about PRs that depend on another, I'm changing the base branch to dev and removing other assignments.

File: src/main/java/org/opentripplanner/middleware/utils/DateTimeUtils.java [hunk 1]
```diff
@@ -153,6 +154,13 @@ public static ZoneId getOtpZoneId() {
         return ZoneId.of(otpTzId);
     }
 
+    /**
+     * Converts a {@link LocalDateTime} on OTP's time zone to epoch milliseconds.
```
Comment (landonreed) [inline src/main/java/org/opentripplanner/middleware/utils/DateTimeUtils.java]: on -> in

File: src/main/java/org/opentripplanner/middleware/utils/ItineraryUtils.java [hunk 2]
```diff
@@ -176,6 +178,42 @@ public static boolean itinerariesMatch(Itinerary referenceItinerary, Itinerary c
...
+    /**
+     * Checks that the specified itinerary is on the same day as the specified date/time.
+     * @param itinerary the itinerary to check.
+     * @param requestDateTime the request date/time to check, in the OTP's time zone.
+     * @param tripIsArriveBy true to check the itinerary endtime, false to check the startTime.
+     * @return true if the itinerary's startTime or endTime is one the same day as the day of the specified date and time.
+     */
+    public static boolean isSameDay(Itinerary itinerary, ZonedDateTime requestDateTime, boolean tripIsArriveBy) {
+        // TODO: Make SERVICE_DAY_START_HOUR an optional config parameter.
+        final int SERVICE_DAY_START_HOUR = 3;
```
Comment (landonreed) [inline src/main/java/org/opentripplanner/middleware/utils/ItineraryUtils.java]: I'd go ahead and make this an optional config param.

File: src/main/java/org/opentripplanner/middleware/utils/ItineraryUtils.java [hunk 3]
```diff
@@ -176,6 +178,42 @@ public static boolean itinerariesMatch(Itinerary referenceItinerary, Itinerary c
...
     }
 
+    /**
+     * Checks that the specified itinerary is on the same day as the specified date/time.
+     * @param itinerary the itinerary to check.
+     * @param requestDateTime the request date/time to check, in the OTP's time zone.
+     * @param tripIsArriveBy true to check the itinerary endtime, false to check the startTime.
+     * @return true if the itinerary's startTime or endTime is one the same day as the day of the specified date and time.
+     */
+    public static boolean isSameDay(Itinerary itinerary, ZonedDateTime requestDateTime, boolean tripIsArriveBy) {
```
Comment (landonreed) [inline src/main/java/org/opentripplanner/middleware/utils/ItineraryUtils.java]: I'd suggest changing the `requestDateTime` arg name to `dateTime`, `isSameDay` to `occursOnServiceDay`, and `tripIsArriveBy` to `arriveBy`.  Javadoc should change accordingly.

Also, wild thought: instead of passing around the arriveBy boolean, should we just add it as a field on `Itinerary`? cc @evansiroky

File: src/main/java/org/opentripplanner/middleware/utils/ItineraryUtils.java [hunk 4]
```diff
@@ -176,6 +178,42 @@ public static boolean itinerariesMatch(Itinerary referenceItinerary, Itinerary c
...
+        // TODO: Make SERVICE_DAY_START_HOUR an optional config parameter.
+        final int SERVICE_DAY_START_HOUR = 3;
+        DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern(DEFAULT_DATE_FORMAT_PATTERN);
```
Comment (landonreed) [inline src/main/java/org/opentripplanner/middleware/utils/ItineraryUtils.java]: We construct default formatters in a couple of places. Opportunity to store a formatter on/import from DateTimeUtils instead? EDIT: It actually looks like this is unused?

File: src/main/java/org/opentripplanner/middleware/models/ItineraryExistence.java [hunk 5]
```diff
@@ -178,11 +185,14 @@ public void checkExistence() {
             // Handle response if valid itineraries exist.
             if (plan != null && plan.itineraries != null) {
                 for (Itinerary itineraryCandidate : plan.itineraries) {
-                    // If a matching itinerary is found, save the date with the matching itinerary.
-                    // The matching itinerary will replace the original trip.itinerary.
-                    if (ItineraryUtils.itinerariesMatch(referenceItinerary, itineraryCandidate)) {
-                        result.handleValidDate(otpRequest.date, itineraryCandidate);
-                        hasMatchingItinerary = true;
+                    // Make sure itinerary is same day as request date
+                    if (ItineraryUtils.isSameDay(itineraryCandidate, otpRequest.date, tripIsArriveBy)) {
```
Comment (landonreed) [inline src/main/java/org/opentripplanner/middleware/models/ItineraryExistence.java]: Could you change `OtpRequest#date` to `OtpRequest#requestDateTime`? I'm finding its current name kind of confusing (probably originally my mistake!).

File: src/main/java/org/opentripplanner/middleware/utils/ItineraryUtils.java [hunk 6]
```diff
@@ -176,6 +178,42 @@ public static boolean itinerariesMatch(Itinerary referenceItinerary, Itinerary c
...
+
+        LocalDate requestLocalDate = requestDateTime.toLocalDate();
+        return (
+            requestLocalDate.equals(startDateTime.toLocalDate()) &&
+            startDateTime.getHour() >= SERVICE_DAY_START_HOUR
+        ) || (
+            // Trips starting between 12am and 2:59am next day are considered same-day.
+            requestLocalDate.equals(startDateTimeDayBefore.toLocalDate()) &&
+            startDateTimeDayBefore.getHour() < SERVICE_DAY_START_HOUR
+        );
```
Comment (landonreed) [inline src/main/java/org/opentripplanner/middleware/utils/ItineraryUtils.java]: I'm not a big fan of this inlined return statement.

File: src/main/java/org/opentripplanner/middleware/utils/ItineraryUtils.java [hunk 7]
```diff
@@ -176,6 +178,42 @@ public static boolean itinerariesMatch(Itinerary referenceItinerary, Itinerary c
...
+        // then consider the request to have been made the day before.
+        // To compensate, advance startDate by one day.
+        int hour = requestDateTime.toLocalTime().getHour();
+        if (hour < SERVICE_DAY_START_HOUR) {
+            startDateTime = startDateTime.plusDays(1);
+        }
+
+        ZonedDateTime startDateTimeDayBefore = startDateTime.minusDays(1);
+
+        LocalDate requestLocalDate = requestDateTime.toLocalDate();
```
Comment (landonreed) [inline src/main/java/org/opentripplanner/middleware/utils/ItineraryUtils.java:207]: Why do we convert to LocalDate for these checks? Please add a comment.

**Review by landonreed — CHANGES_REQUESTED** [review]
A few comments here and some changes in #112.

File: src/main/java/org/opentripplanner/middleware/utils/ItineraryUtils.java (hunk 6 above)
Comment (landonreed) [reply src/main/java/org/opentripplanner/middleware/utils/ItineraryUtils.java]: Addressed in #112.

File: src/main/java/org/opentripplanner/middleware/utils/ItineraryUtils.java (hunk 4 above)
Comment (landonreed) [reply src/main/java/org/opentripplanner/middleware/utils/ItineraryUtils.java]: Removed in #112.

File: src/main/java/org/opentripplanner/middleware/utils/ItineraryUtils.java (hunk 3 above)
Comment (landonreed) [reply src/main/java/org/opentripplanner/middleware/utils/ItineraryUtils.java]: Partially addressed in #112.

File: src/main/java/org/opentripplanner/middleware/models/ItineraryExistence.java (hunk 5 above)
Comment (binh-dam-ibigroup) [reply src/main/java/org/opentripplanner/middleware/models/ItineraryExistence.java]: Updated in https://github.com/ibi-group/otp-middleware/pull/102/commits/911c618356112c4db4b089e158aab92ab6c23062.

File: src/main/java/org/opentripplanner/middleware/utils/ItineraryUtils.java (hunk 2 above)
Comment (binh-dam-ibigroup) [reply src/main/java/org/opentripplanner/middleware/utils/ItineraryUtils.java]: It is an optonal config param in https://github.com/ibi-group/otp-middleware/pull/102/commits/911c618356112c4db4b089e158aab92ab6c23062.

File: src/main/java/org/opentripplanner/middleware/utils/DateTimeUtils.java (hunk 1 above)
Comment (binh-dam-ibigroup) [reply src/main/java/org/opentripplanner/middleware/utils/DateTimeUtils.java]: fixed in https://github.com/ibi-group/otp-middleware/pull/102/commits/911c618356112c4db4b089e158aab92ab6c23062.

**Comment by binh-dam-ibigroup** [comment]
I'm going ahead and block this PR pending merging of #109, which should address CI test failures regarding saving trips.

**Review by br648 — APPROVED** [review]
LGTM

**Review by landonreed — APPROVED** [review]

**Review by evansiroky — CHANGES_REQUESTED** [review]
Please fix failing travis build.

**Comment by binh-dam-ibigroup** [comment]
> Please fix failing travis build.

@evansiroky I reran the failing build and it passes now.

File: src/main/java/org/opentripplanner/middleware/tripMonitor/jobs/CheckMonitoredTrip.java [hunk 8]
```diff
@@ -46,11 +45,9 @@
 public class CheckMonitoredTrip implements Runnable {
     private static final Logger LOG = LoggerFactory.getLogger(CheckMonitoredTrip.class);
 
-    private static final DateTimeFormatter DATE_FORMATTER = DateTimeFormatter.ofPattern(
-        DateTimeUtils.DEFAULT_DATE_FORMAT_PATTERN
-    );
-
     public final MonitoredTrip trip;
+    public int departureDelay;
+    public int arrivalDelay;
```
Comment (evansiroky) [inline src/main/java/org/opentripplanner/middleware/tripMonitor/jobs/CheckMonitoredTrip.java]: Where did these come from? They aren't used anywhere.

File: src/test/java/org/opentripplanner/middleware/ApiUserFlowTest.java [hunk 9]
```diff
@@ -196,12 +197,21 @@ public void canSimulateApiUserFlow() throws URISyntaxException, JsonProcessingEx
...
         HttpResponse<String> createTripResponseAsApiUser = makeRequest(
             MONITORED_TRIP_PATH,
             JsonUtils.toJson(monitoredTrip),
             apiUserHeaders,
             HttpUtils.REQUEST_METHOD.POST
         );
+
+        // After POST is complete, reset mock OTP responses for subsequent tests.
+        TestUtils.resetOtpMocks();
+
```
Comment (evansiroky) [inline src/test/java/org/opentripplanner/middleware/ApiUserFlowTest.java]: These should be moved outside of this test into before/after test methods, especially the resetOtpMocks call. If the `makeRequest` call fails, the OTP mocks won't be reset.

File: src/test/java/org/opentripplanner/middleware/GetMonitoredTripsTest.java [hunk 10]
```diff
@@ -114,52 +114,59 @@ public static void tearDown() {
...
+        TestUtils.setupOtpMocks(ItineraryUtilsTest.createMockOtpResponsesForTripExistence());
+
+        HttpResponse<String> createTripResponse = mockAuthenticatedRequest(MONITORED_TRIP_PATH,
+            JsonUtils.toJson(monitoredTrip),
+            otpUser,
+            HttpUtils.REQUEST_METHOD.POST
+        );
+
+        // After POST is complete, reset mock OTP responses for subsequent tests.
+        TestUtils.resetOtpMocks();
```
Comment (evansiroky) [inline src/test/java/org/opentripplanner/middleware/GetMonitoredTripsTest.java]: The resetOTPMocks should be moved into an after method so that it always runs even if the test fails.

File: src/main/java/org/opentripplanner/middleware/models/ItineraryExistence.java [hunk 11]
```diff
@@ -178,17 +185,20 @@ public void checkExistence() {
...
-                    // If a matching itinerary is found, save the date with the matching itinerary.
-                    // The matching itinerary will replace the original trip.itinerary.
-                    if (ItineraryUtils.itinerariesMatch(referenceItinerary, itineraryCandidate)) {
-                        result.handleValidDate(otpRequest.date, itineraryCandidate);
-                        hasMatchingItinerary = true;
+                    // Make sure itinerary is same day as request date
+                    if (ItineraryUtils.occursOnSameServiceDay(itineraryCandidate, otpRequest.dateTime, tripIsArriveBy)) {
+                        // If a matching itinerary is found, save the date with the matching itinerary.
+                        // The matching itinerary will replace the original trip.itinerary.
+                        if (ItineraryUtils.itinerariesMatch(referenceItinerary, itineraryCandidate)) {
```
Comment (evansiroky) [inline src/main/java/org/opentripplanner/middleware/models/ItineraryExistence.java]: Seems like these could be combined into a single if statement

File: src/main/java/org/opentripplanner/middleware/utils/ItineraryUtils.java [hunk 12]
```diff
@@ -176,6 +178,37 @@ public static boolean itinerariesMatch(Itinerary referenceItinerary, Itinerary c
         return true;
     }
 
+    /**
+     * Checks that the specified itinerary is on the same day as the specified date/time.
+     * @param itinerary the itinerary to check.
+     * @param dateTime the request date/time to check, in the OTP's time zone.
```
Comment (evansiroky) [inline src/main/java/org/opentripplanner/middleware/utils/ItineraryUtils.java]: Can we rename this to be `requestDateTime`?

File: src/test/java/org/opentripplanner/middleware/utils/ItineraryUtilsTest.java [hunk 13]
```diff
@@ -43,32 +49,66 @@
...
+    private static final Itinerary DEFAULT_ITINERARY = OTP_DISPATCHER_PLAN_RESPONSE.getResponse().plan.itineraries.get(0);
+    public static final ZoneId OTP_ZONE_ID = DateTimeUtils.getOtpZoneId();
 
     @BeforeAll
-    public static void setup() throws IOException {
+    public static void setup() {
         TestUtils.mockOtpServer();
+    }
 
+    public static OtpDispatcherResponse initializeMockPlanResponse(String path) {
```
Comment (evansiroky) [inline src/test/java/org/opentripplanner/middleware/utils/ItineraryUtilsTest.java:91]: <strike>This method does not appear to be used anymore.</strike> My IntelliJ is messed up.

File: src/test/java/org/opentripplanner/middleware/utils/ItineraryUtilsTest.java [hunk 14]
```diff
@@ -43,32 +49,66 @@
...
+        } catch (IOException e) {
+            e.printStackTrace();
+        }
+        return new OtpDispatcherResponse(mockPlanResponse, DEFAULT_PLAN_URI);
+    }
 
-        otpDispatcherPlanResponse = new OtpDispatcherResponse(mockPlanResponse, DEFAULT_PLAN_URI);
-        otpDispatcherPlanErrorResponse = new OtpDispatcherResponse(mockErrorResponse, DEFAULT_PLAN_URI);
-        defaultItinerary = otpDispatcherPlanResponse.getResponse().plan.itineraries.get(0);
+    public static List<OtpResponse> createMockOtpResponsesForTripExistence() {
```
Comment (evansiroky) [inline src/test/java/org/opentripplanner/middleware/utils/ItineraryUtilsTest.java]: This method is not used anywhere in this file. Instead, it is referenced from `ApiUserFlowTest` and `GetMonitoredTripsTest`. To me, this seems to be some kind of function that ought to be placed in some kind of Util class so that there are less util functions in classes like these that contain tests. This should probably be moved to some class with mainly Util functions. I went ahead and made https://github.com/ibi-group/otp-middleware/pull/119 that reogranizes a bunch of test files. Assuming that PR is accepted, the best spot for this would be within the `OtpTestUtils` class. However, in order to move this along, I think it'd be fine to just chuck this one into the `TestUtils` class for now and I'd be fine with reorganizing as a part of #119.

File: src/test/java/org/opentripplanner/middleware/utils/ItineraryUtilsTest.java [hunk 15]
```diff
@@ -77,70 +117,99 @@ public void tearDownAfterTest() {
...
+
     /**
-     * Test case in which at least one itinerary does not exist,
-     * and therefore result.allCheckedDatesAreValid should be false.
+     * @return The new {@link Date} object with the date portion set to the specified {@link LocalDate} in OTP timezone.
      */
-    @Test
-    public void canCheckAtLeastOneTripDoesNotExist() throws URISyntaxException {
-        MonitoredTrip trip = makeTestTrip();
+    public static Date getNewItineraryDate(Date itineraryDate, LocalDate date) {
```
Comment (evansiroky) [inline src/test/java/org/opentripplanner/middleware/utils/ItineraryUtilsTest.java]: Same comment as https://github.com/ibi-group/otp-middleware/pull/102#discussion_r534843634.

File: src/test/java/org/opentripplanner/middleware/utils/ItineraryUtilsTest.java [hunk 16]
```diff
@@ -77,70 +117,99 @@ public void tearDownAfterTest() {
...
+        Instant startInstant = itineraryDate.toInstant();
 
-        // Set mocks to a list of responses, one without an itinerary.
-        OtpResponse resp = otpDispatcherPlanResponse.getResponse();
-        TestUtils.setupOtpMocks(List.of(resp, resp, resp, otpDispatcherPlanErrorResponse.getResponse(), resp));
+        return Date.from(LocalDateTime.of(
+            date,
+            LocalTime.ofInstant(startInstant, OTP_ZONE_ID)
+        ).toInstant(OTP_ZONE_ID.getRules().getOffset(startInstant)));
```
Comment (evansiroky) [inline src/test/java/org/opentripplanner/middleware/utils/ItineraryUtilsTest.java]: I'm not a huge fan of using offsets. I suppose this might be safe to use since the offset is being retrieved for a certain point in time. But here is an alternative implementation of this:

```java
return new Date(
    ZonedDateTime.ofInstant(itineraryDate.toInstant(), DateTimeUtils.getOtpZoneId())
        .withYear(date.getYear())
        .withMonth(date.getMonthValue())
        .withDayOfMonth(date.getDayOfMonth())
        .toInstant()
        .toEpochMilli()
);
```

File: src/test/java/org/opentripplanner/middleware/utils/ItineraryUtilsTest.java (hunk 15 above)
Comment (evansiroky) [reply src/test/java/org/opentripplanner/middleware/utils/ItineraryUtilsTest.java]: Actually, maybe this is ok to keep in this file since it isn't used elsewhere.

**Review by evansiroky — CHANGES_REQUESTED** [review]
A few recommendations for refactors, but please refactor the calling of resetOtpMocks in the places where this was noted.

File: src/test/java/org/opentripplanner/middleware/utils/ItineraryUtilsTest.java (hunk 16 above)
Comment (binh-dam-ibigroup) [reply src/test/java/org/opentripplanner/middleware/utils/ItineraryUtilsTest.java]: Updated in https://github.com/ibi-group/otp-middleware/pull/102/commits/98f91c7d7043e0039a39a1855dc3e40befbf178e. I agree, the offset and rule thing feels complicated, and I was trying to key in the date parts, but there is a sleek syntax using `.with(date)` that takes care of it.

File: src/test/java/org/opentripplanner/middleware/utils/ItineraryUtilsTest.java (hunk 14 above)
Comment (binh-dam-ibigroup) [reply src/test/java/org/opentripplanner/middleware/utils/ItineraryUtilsTest.java]: Updated in https://github.com/ibi-group/otp-middleware/pull/102/commits/98f91c7d7043e0039a39a1855dc3e40befbf178e. I moved it to `TestUtils`.

File: src/main/java/org/opentripplanner/middleware/utils/ItineraryUtils.java (hunk 12 above)
Comment (binh-dam-ibigroup) [reply src/main/java/org/opentripplanner/middleware/utils/ItineraryUtils.java]: Updated in https://github.com/ibi-group/otp-middleware/pull/102/commits/98f91c7d7043e0039a39a1855dc3e40befbf178e.

File: src/main/java/org/opentripplanner/middleware/models/ItineraryExistence.java (hunk 11 above)
Comment (binh-dam-ibigroup) [reply src/main/java/org/opentripplanner/middleware/models/ItineraryExistence.java]: https://github.com/ibi-group/otp-middleware/pull/102/commits/98f91c7d7043e0039a39a1855dc3e40befbf178e.

File: src/main/java/org/opentripplanner/middleware/tripMonitor/jobs/CheckMonitoredTrip.java (hunk 8 above)
Comment (binh-dam-ibigroup) [reply src/main/java/org/opentripplanner/middleware/tripMonitor/jobs/CheckMonitoredTrip.java]: Probably copy/paste. I removed it in https://github.com/ibi-group/otp-middleware/pull/102/commits/98f91c7d7043e0039a39a1855dc3e40befbf178e.

File: src/test/java/org/opentripplanner/middleware/ApiUserFlowTest.java (hunk 9 above)
Comment (binh-dam-ibigroup) [reply src/test/java/org/opentripplanner/middleware/ApiUserFlowTest.java]: I tried moving the reset call in https://github.com/ibi-group/otp-middleware/pull/102/commits/98f91c7d7043e0039a39a1855dc3e40befbf178e and that caused failures, because there are other mock OTP calls that happen before the test exits, so I'm resetting mocks here (see https://github.com/ibi-group/otp-middleware/pull/102/commits/53ef5e41fdf5e4022d3c585e414c05f8f078d9f9 and https://github.com/ibi-group/otp-middleware/pull/102/commits/51f7dbcff06174eb82ac377d7baae340b0c9f6d5) in addition to resetting inside `@AfterEach`.

File: src/test/java/org/opentripplanner/middleware/GetMonitoredTripsTest.java (hunk 10 above)
Comment (binh-dam-ibigroup) [reply src/test/java/org/opentripplanner/middleware/GetMonitoredTripsTest.java]: Same remark as https://github.com/ibi-group/otp-middleware/pull/102#discussion_r535584866.

**Review by evansiroky — APPROVED** [review]
