### PR TITLE
Prevent conversion of non-plan OTP responses to POJO

### LINKED ISSUE #73: POJO conversion errors
## Observed behavior

In just two days, over 1100 exceptions of the type below are reported to bugsnag on the FDOT middleware instance.
These exceptions appear to be raised by a call to the `park_and_ride` OTP proxy endpoint in the middleware.

```log
[1;31mERROR[0;39m 2020-09-11T17:51:51.695 [33m[qtp702453097-20061][0;39m [34mo.o.m.bugsnag.BugsnagReporter(BugsnagReporter.java:51)[0;39m Unable to get POJO from json for Response
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `org.opentripplanner.middleware.otp.response.Response` out of START_ARRAY token
 at [Source: (String)"[{"name":"P+R","x":-81.36548775,"y":28.4528734},{"name":"P+R","x":-81.274944,"y":28.911900600000003},{"name":"P+R","x":-81.7390652,"y":28.540740550000002},{"name":"P+R","x":-81.13372815,"y":28.561692100000002}]"; line: 1, column: 1]
```

These errors are **potentially** resulting in a "too many open files" exception that prevents the server from fulfilling any request (see #70).

## Expected behavior

These exceptions should not be raised or reported.

## Steps to reproduce the problem

- Run the `dev` branch of otp-middleware locally.
- Run OTP-RR against the local middleware and open `http://localhost:9966`.
- An error log similar to the above is shown.

### PR DESCRIPTION
**Pull request by binh-dam-ibigroup**
### Checklist

- [X] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [X] Any modified or new methods or classes have helpful JavaDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [na] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing

### Description

This PR fixes #73. A new test class and a `park_and_ride` mock response are added to guard against #73.

### CODE REVIEW

**Review by evansiroky — APPROVED** [review]

File: src/test/java/org/opentripplanner/middleware/otp/OtpDispatcherResponseTest.java [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+import org.opentripplanner.middleware.utils.FileUtils;
+
+import java.io.IOException;
+
+import static org.opentripplanner.middleware.TestUtils.TEST_RESOURCE_PATH;
+import static org.opentripplanner.middleware.otp.OtpDispatcher.OTP_PLAN_ENDPOINT;
+
+public class OtpDispatcherResponseTest {
+    @Test
+    public void toStringShouldExludeResponseFieldIfNotCallingPlan() throws IOException {
```
Comment (br648) [inline src/test/java/org/opentripplanner/middleware/otp/OtpDispatcherResponseTest.java]: Typo Exlude: Exclude.

**Review by br648 — APPROVED** [review]
One minor typo, but looks good so approving.

File: src/test/java/org/opentripplanner/middleware/otp/OtpDispatcherResponseTest.java (hunk 1 above)
Comment (binh-dam-ibigroup) [reply src/test/java/org/opentripplanner/middleware/otp/OtpDispatcherResponseTest.java]: Good catch! Thanks.
